"""Add coordinate columns

Revision ID: 631e4ef94cee
Revises: 591ec5b4402d
Create Date: 2026-03-06 20:13:10.739560

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "631e4ef94cee"
down_revision: Union[str, Sequence[str], None] = "591ec5b4402d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("zefix_companies", sa.Column("lat", sa.Float(), nullable=True))
    op.add_column("zefix_companies", sa.Column("lng", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zefix_companies", "lng")
    op.drop_column("zefix_companies", "lat")
    # ### end Alembic commands ###
