"""Add zefix table

Revision ID: 7200d5b261e8
Revises:
Create Date: 2026-03-06 16:49:28.384192

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7200d5b261e8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zefix_companies",
        sa.Column("uid", sa.String(length=15), nullable=False),
        sa.Column("org", sa.Text(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("legal_form", sa.String(length=4), nullable=False),
        sa.Column("canton", sa.String(length=2), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=True),
        sa.Column("zip", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_lang", sa.String(length=10), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zefix_companies")
    # ### end Alembic commands ###
