# NOGA / NACE taxonomy data shared across the application.
# Each section entry: (code, name, description)
# Each division entry: (code, section_code, name, description)

NOGA_SECTIONS: list[tuple[str, str, str]] = [
    (
        "A",
        "Agriculture, Forestry and Fishing",
        "Farming, crop cultivation, livestock raising, forestry, logging, fishing, aquaculture, hunting.",
    ),
    (
        "B",
        "Mining and Quarrying",
        "Extraction of coal, crude oil, natural gas, metal ores, stone, sand, gravel, salt, mining support services.",
    ),
    (
        "C",
        "Manufacturing",
        "Production and transformation of raw materials into finished goods: food, beverages, textiles, chemicals, metals, machinery, electronics, vehicles, pharmaceuticals.",
    ),
    (
        "D",
        "Electricity, Gas, Steam and Air Conditioning Supply",
        "Generation, transmission and distribution of electricity, gas, steam, hot water, air conditioning, renewable energy, solar, wind power.",
    ),
    (
        "E",
        "Water Supply; Sewerage, Waste Management and Remediation",
        "Water collection, treatment and distribution, sewerage, waste collection, recycling, environmental cleanup, remediation.",
    ),
    (
        "F",
        "Construction",
        "Building construction, civil engineering, road building, installation of electrical, plumbing and HVAC systems, renovation, demolition, real estate development.",
    ),
    (
        "G",
        "Wholesale and Retail Trade; Repair of Motor Vehicles",
        "Sale of goods to consumers and businesses, wholesale trade, retail shops, supermarkets, e-commerce, car dealerships, vehicle repair.",
    ),
    (
        "H",
        "Transportation and Storage",
        "Road freight, trucking, taxis, rail transport, shipping, airlines, warehousing, logistics, courier and postal services, pipeline transport.",
    ),
    (
        "I",
        "Accommodation and Food Service Activities",
        "Hotels, restaurants, bars, cafés, catering, food delivery, resorts, camping, short-term accommodation.",
    ),
    (
        "J",
        "Information and Communication",
        "Software development, IT consulting, web development, cybersecurity, telecommunications, internet services, publishing, broadcasting, streaming, data processing, SaaS.",
    ),
    (
        "K",
        "Financial and Insurance Activities",
        "Banking, investment banking, asset management, insurance, reinsurance, pension funds, financial advisory, venture capital, private equity, stock exchange.",
    ),
    (
        "L",
        "Real Estate Activities",
        "Buying, selling and renting real estate, property management, real estate agencies, development of residential and commercial properties.",
    ),
    (
        "M",
        "Professional, Scientific and Technical Activities",
        "Legal services, accounting, auditing, management consulting, engineering, architecture, R&D, advertising, market research, veterinary services, translation.",
    ),
    (
        "N",
        "Administrative and Support Service Activities",
        "Office administration, employment agencies, travel agencies, security services, cleaning, landscaping, business process outsourcing, call centres, facility management.",
    ),
    (
        "O",
        "Public Administration and Defence; Compulsory Social Security",
        "Government administration, defence, police, courts, fire services, social security administration, public authority.",
    ),
    (
        "P",
        "Education",
        "Primary and secondary schools, universities, vocational training, language courses, tutoring, e-learning, professional development, sports instruction.",
    ),
    (
        "Q",
        "Human Health and Social Work Activities",
        "Hospitals, clinics, medical practices, dental offices, nursing homes, social care, mental health services, disability support, pharmacies.",
    ),
    (
        "R",
        "Arts, Entertainment and Recreation",
        "Performing arts, theatres, museums, galleries, sports clubs, fitness centres, amusement parks, gambling, film production, creative arts.",
    ),
    (
        "S",
        "Other Service Activities",
        "Membership organisations, trade unions, religious organisations, repair of personal goods, laundry, hairdressing, beauty salons, funeral services.",
    ),
    (
        "T",
        "Activities of Households as Employers",
        "Private households employing domestic staff such as cleaners, cooks, gardeners, childminders or nannies.",
    ),
    (
        "U",
        "Activities of Extraterritorial Organisations and Bodies",
        "International organisations, embassies, consulates, United Nations agencies, NATO, diplomatic missions.",
    ),
]

# Each entry: (code, section_code, name, description)
NOGA_DIVISIONS: list[tuple[str, str, str, str]] = [
    (
        "01",
        "A",
        "Crop and animal production, hunting and related service activities",
        "Farming cereals, vegetables, fruit, vines, livestock, poultry, dairy, eggs, hunting.",
    ),
    (
        "02",
        "A",
        "Forestry and logging",
        "Growing and harvesting timber, forest management, production of roundwood, wood supply.",
    ),
    (
        "03",
        "A",
        "Fishing and aquaculture",
        "Sea and freshwater fishing, fish farming, shellfish farming, aquaculture.",
    ),
    (
        "05",
        "B",
        "Mining of coal and lignite",
        "Extraction of hard coal, lignite, underground and surface mining.",
    ),
    (
        "06",
        "B",
        "Extraction of crude petroleum and natural gas",
        "Oil and gas extraction, offshore drilling, liquefied natural gas.",
    ),
    (
        "07",
        "B",
        "Mining of metal ores",
        "Iron ore, copper, gold, silver, uranium, bauxite mining.",
    ),
    (
        "08",
        "B",
        "Other mining and quarrying",
        "Quarrying stone, sand, gravel, clay, salt, chemical minerals, peat.",
    ),
    (
        "09",
        "B",
        "Mining support service activities",
        "Drilling, field services for oil, gas and mining operations.",
    ),
    (
        "10",
        "C",
        "Manufacture of food products",
        "Processing meat, fish, fruit, vegetables, oils, dairy, flour, bakery, sugar, pasta, spices, coffee, tea.",
    ),
    (
        "11",
        "C",
        "Manufacture of beverages",
        "Distilling spirits, brewing beer, winemaking, soft drinks, mineral water, juice.",
    ),
    (
        "12",
        "C",
        "Manufacture of tobacco products",
        "Cigarettes, cigars, pipe tobacco, tobacco processing.",
    ),
    (
        "13",
        "C",
        "Manufacture of textiles",
        "Spinning, weaving, knitting fabrics, technical textiles, yarn, thread.",
    ),
    (
        "14",
        "C",
        "Manufacture of wearing apparel",
        "Clothing, garments, fur products, fashion manufacturing, outerwear.",
    ),
    (
        "15",
        "C",
        "Manufacture of leather and related products",
        "Leather tanning, luggage, handbags, footwear, saddlery.",
    ),
    (
        "16",
        "C",
        "Manufacture of wood and wood products",
        "Sawmilling, wood panels, parquet, joinery, carpentry, wooden packaging, cork.",
    ),
    (
        "17",
        "C",
        "Manufacture of paper and paper products",
        "Pulp, paper, cardboard, packaging, paper stationery, tissue.",
    ),
    (
        "18",
        "C",
        "Printing and reproduction of recorded media",
        "Printing books, newspapers, magazines, labels, reproduction of recorded media.",
    ),
    (
        "19",
        "C",
        "Manufacture of coke and refined petroleum products",
        "Oil refining, fuel production, petrochemical feedstocks, coke ovens.",
    ),
    (
        "20",
        "C",
        "Manufacture of chemicals and chemical products",
        "Industrial chemicals, fertilisers, plastics raw materials, paints, soap, detergents, cosmetics, agrochemicals.",
    ),
    (
        "21",
        "C",
        "Manufacture of basic pharmaceutical products and preparations",
        "Drug development, pharmaceutical manufacturing, vaccines, active pharmaceutical ingredients, medicinal products.",
    ),
    (
        "22",
        "C",
        "Manufacture of rubber and plastic products",
        "Tyres, rubber goods, plastic packaging, pipes, plastic profiles, foam.",
    ),
    (
        "23",
        "C",
        "Manufacture of other non-metallic mineral products",
        "Glass, ceramics, cement, concrete, bricks, tiles, refractory materials, abrasives.",
    ),
    (
        "24",
        "C",
        "Manufacture of basic metals",
        "Iron, steel, aluminium, copper, precious metals smelting and casting.",
    ),
    (
        "25",
        "C",
        "Manufacture of fabricated metal products",
        "Metal structures, tanks, weapons, cutlery, tools, metal hardware, springs, fasteners, metal treatment.",
    ),
    (
        "26",
        "C",
        "Manufacture of computer, electronic and optical products",
        "Semiconductors, computers, telecom equipment, consumer electronics, instruments, medical devices, watches, optical products.",
    ),
    (
        "27",
        "C",
        "Manufacture of electrical equipment",
        "Electric motors, generators, batteries, cables, wiring, lighting, household appliances, switchgear.",
    ),
    (
        "28",
        "C",
        "Manufacture of machinery and equipment",
        "General-purpose and special-purpose machinery, agricultural machines, machine tools, industrial equipment, pumps, compressors.",
    ),
    (
        "29",
        "C",
        "Manufacture of motor vehicles, trailers and semi-trailers",
        "Cars, trucks, buses, trailers, automotive parts and accessories.",
    ),
    (
        "30",
        "C",
        "Manufacture of other transport equipment",
        "Ships, boats, aircraft, spacecraft, railway locomotives, motorcycles, bicycles.",
    ),
    (
        "31",
        "C",
        "Manufacture of furniture",
        "Chairs, sofas, tables, beds, office furniture, kitchen furniture, mattresses.",
    ),
    (
        "32",
        "C",
        "Other manufacturing",
        "Jewellery, musical instruments, sports goods, games, toys, medical devices, brooms, pens.",
    ),
    (
        "33",
        "C",
        "Repair and installation of machinery and equipment",
        "Repair and maintenance of industrial machinery, electronic equipment, instruments, vehicles.",
    ),
    (
        "35",
        "D",
        "Electricity, gas, steam and air conditioning supply",
        "Power generation, electricity distribution, gas supply, steam and hot water supply, district heating, solar, wind, hydropower.",
    ),
    (
        "36",
        "E",
        "Water collection, treatment and supply",
        "Drinking water production, water treatment, water distribution networks.",
    ),
    (
        "37",
        "E",
        "Sewerage",
        "Sewage collection, wastewater treatment, drainage systems.",
    ),
    (
        "38",
        "E",
        "Waste collection, treatment and disposal; materials recovery",
        "Rubbish collection, recycling, waste treatment, landfill, material recovery, scrap.",
    ),
    (
        "39",
        "E",
        "Remediation activities and other waste management services",
        "Soil decontamination, cleanup of polluted sites, environmental remediation, hazardous waste.",
    ),
    (
        "41",
        "F",
        "Construction of buildings",
        "Residential and commercial building construction, general contractors, development of apartment and office buildings.",
    ),
    (
        "42",
        "F",
        "Civil engineering",
        "Roads, motorways, bridges, tunnels, railways, pipelines, power lines, harbours, dams.",
    ),
    (
        "43",
        "F",
        "Specialised construction activities",
        "Demolition, electrical installation, plumbing, heating, HVAC, plastering, painting, glazing, roofing, tiling, scaffolding.",
    ),
    (
        "45",
        "G",
        "Wholesale and retail trade and repair of motor vehicles",
        "Car dealers, motorcycle dealers, petrol stations, vehicle spare parts, car repair garages.",
    ),
    (
        "46",
        "G",
        "Wholesale trade, except of motor vehicles",
        "Wholesale of food, beverages, textiles, machinery, electronics, chemicals, pharmaceuticals, agricultural goods, raw materials.",
    ),
    (
        "47",
        "G",
        "Retail trade, except of motor vehicles",
        "Supermarkets, grocery stores, clothing shops, electronics retailers, pharmacies, bookshops, e-commerce, department stores.",
    ),
    (
        "49",
        "H",
        "Land transport and transport via pipelines",
        "Road freight, trucking, taxis, ride-hailing, buses, rail passenger and freight, pipeline transport.",
    ),
    (
        "50",
        "H",
        "Water transport",
        "Sea shipping, inland waterway transport, ferries, cargo ships.",
    ),
    (
        "51",
        "H",
        "Air transport",
        "Airlines, cargo air transport, charter flights, airports.",
    ),
    (
        "52",
        "H",
        "Warehousing and support activities for transportation",
        "Warehousing, container terminals, freight forwarding, logistics providers, customs brokers.",
    ),
    (
        "53",
        "H",
        "Postal and courier activities",
        "Postal services, courier, parcel delivery, express mail, last-mile delivery.",
    ),
    (
        "55",
        "I",
        "Accommodation",
        "Hotels, resorts, hostels, camping, holiday rentals, bed and breakfast, serviced apartments.",
    ),
    (
        "56",
        "I",
        "Food and beverage service activities",
        "Restaurants, cafés, bars, canteens, catering companies, fast food, food delivery services.",
    ),
    (
        "58",
        "J",
        "Publishing activities",
        "Publishing books, newspapers, magazines, directories, software, online content, e-books.",
    ),
    (
        "59",
        "J",
        "Motion picture, video and television programme production",
        "Film production, video production, TV programmes, animation, sound recording, music publishing.",
    ),
    (
        "60",
        "J",
        "Programming and broadcasting activities",
        "Radio and television broadcasting, streaming platforms, podcasting.",
    ),
    (
        "61",
        "J",
        "Telecommunications",
        "Fixed-line and mobile phone networks, internet service providers, satellite communications, cable TV operators.",
    ),
    (
        "62",
        "J",
        "Computer programming, consultancy and related activities",
        "Software development, web development, app development, IT consulting, systems integration, cybersecurity, DevOps, cloud services.",
    ),
    (
        "63",
        "J",
        "Information service activities",
        "Data processing, web hosting, search engines, data analytics, online portals, SaaS platforms, digital data services.",
    ),
    (
        "64",
        "K",
        "Financial service activities, except insurance and pension funding",
        "Banks, investment banks, venture capital, private equity, fund management, money transfer, leasing, credit, fintech.",
    ),
    (
        "65",
        "K",
        "Insurance, reinsurance and pension funding",
        "Life insurance, health insurance, property and casualty insurance, reinsurance, pension funds, annuities.",
    ),
    (
        "66",
        "K",
        "Activities auxiliary to financial services and insurance",
        "Financial brokers, stock exchanges, fund administration, financial advisors, insurance brokers, rating agencies.",
    ),
    (
        "68",
        "L",
        "Real estate activities",
        "Buying, selling, renting real estate, property management, real estate development, agencies, property valuation.",
    ),
    (
        "69",
        "M",
        "Legal and accounting activities",
        "Law firms, lawyers, notaries, accountants, auditors, tax advisors, bookkeeping, legal advisory.",
    ),
    (
        "70",
        "M",
        "Activities of head offices; management consultancy",
        "Corporate headquarters, holding companies, management consulting, business strategy, organisational advisory.",
    ),
    (
        "71",
        "M",
        "Architectural and engineering activities; technical testing",
        "Architects, structural engineers, civil engineers, urban planners, surveying, technical testing and inspection, quality control.",
    ),
    (
        "72",
        "M",
        "Scientific research and development",
        "R&D in natural sciences, engineering, biotechnology, social sciences, humanities, medical research, innovation.",
    ),
    (
        "73",
        "M",
        "Advertising and market research",
        "Advertising agencies, PR, branding, market research, media buying, digital marketing, SEO, social media marketing.",
    ),
    (
        "74",
        "M",
        "Other professional, scientific and technical activities",
        "Photography, translation, interpreting, design studios, industrial design, fashion design, exhibition services.",
    ),
    (
        "75",
        "M",
        "Veterinary activities",
        "Animal healthcare, veterinary clinics, animal hospitals, pet care, livestock health.",
    ),
    (
        "77",
        "N",
        "Rental and leasing activities",
        "Car rental, equipment leasing, machinery hire, consumer goods rental, intellectual property licensing.",
    ),
    (
        "78",
        "N",
        "Employment activities",
        "Recruitment agencies, temporary staffing, HR outsourcing, executive search, headhunting, payroll services.",
    ),
    (
        "79",
        "N",
        "Travel agency, tour operator and reservation services",
        "Travel agencies, tour operators, online travel booking platforms, event ticketing, destination management.",
    ),
    (
        "80",
        "N",
        "Security and investigation activities",
        "Security guards, private investigation, alarm monitoring, armoured transport, cybersecurity operations.",
    ),
    (
        "81",
        "N",
        "Services to buildings and landscape activities",
        "Office cleaning, facility management, building maintenance, gardening, landscaping, pest control.",
    ),
    (
        "82",
        "N",
        "Office administrative and business support services",
        "Office administration, secretarial services, call centres, trade fairs, document management, debt collection.",
    ),
    (
        "84",
        "O",
        "Public administration and defence; compulsory social security",
        "Government ministries, municipal administration, police, army, courts, fire brigade, social insurance administration.",
    ),
    (
        "85",
        "P",
        "Education",
        "Primary and secondary schools, universities, vocational training, driving schools, language schools, tutoring, e-learning, professional training.",
    ),
    (
        "86",
        "Q",
        "Human health activities",
        "Hospitals, general practitioners, specialist clinics, dentists, physiotherapists, diagnostic laboratories, home healthcare.",
    ),
    (
        "87",
        "Q",
        "Residential care activities",
        "Nursing homes, residential care for elderly, addiction treatment centres, mental health residential facilities.",
    ),
    (
        "88",
        "Q",
        "Social work activities without accommodation",
        "Day care centres, social counselling, disability support, childcare, community social services, food banks.",
    ),
    (
        "90",
        "R",
        "Creative, arts and entertainment activities",
        "Theatres, concert halls, artists, musicians, writers, circus, cultural events, entertainment production.",
    ),
    (
        "91",
        "R",
        "Libraries, archives, museums and other cultural activities",
        "Public libraries, archives, museums, art galleries, botanical gardens, zoos, historic sites.",
    ),
    (
        "92",
        "R",
        "Gambling and betting activities",
        "Casinos, lotteries, sports betting, online gambling, gaming halls.",
    ),
    (
        "93",
        "R",
        "Sports activities and amusement and recreation activities",
        "Sports clubs, fitness centres, gyms, ski resorts, theme parks, escape rooms, bowling alleys.",
    ),
    (
        "94",
        "S",
        "Activities of membership organisations",
        "Business associations, trade unions, employers organisations, professional bodies, political parties, religious organisations, clubs, NGOs.",
    ),
    (
        "95",
        "S",
        "Repair of computers and personal and household goods",
        "Computer repair, mobile phone repair, appliance repair, shoe repair, watch repair, bicycle repair.",
    ),
    (
        "96",
        "S",
        "Other personal service activities",
        "Hairdressers, barbers, beauty salons, spas, massage, laundry, dry cleaning, funeral services, pet grooming.",
    ),
    (
        "97",
        "T",
        "Activities of households as employers of domestic personnel",
        "Private households employing domestic helpers, cooks, gardeners, nannies, cleaners.",
    ),
    (
        "98",
        "T",
        "Undifferentiated goods- and services-producing activities of private households for own use",
        "Private households producing goods or services for their own consumption without employing others.",
    ),
    (
        "99",
        "U",
        "Activities of extraterritorial organisations and bodies",
        "UN, EU institutions, NATO, embassies, consulates, international NGOs, diplomatic missions, intergovernmental organisations.",
    ),
]

# Pre-built lookup dicts for quick access by code
SECTION_NAME: dict[str, str] = {code: name for code, name, _ in NOGA_SECTIONS}
DIVISION_NAME: dict[str, str] = {code: name for code, _, name, _ in NOGA_DIVISIONS}
DIVISION_SECTION: dict[str, str] = {code: section for code, section, _, _ in NOGA_DIVISIONS}
